---
openapi: 3.0.1
info:
  title: Masterpiece encoder
  version: "1.0"
  description: A gateway to enter masterpiece payment data.
  contact:
    name: 'Online Services Team : DEW'
    url: https://www.environment.sa.gov.au/Home
    email: ""
  license:
    name: For internal use only
    url: https://www.environment.sa.gov.au/Home
paths:
  /api/authentication:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      tags:
      - Auth
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: Successful response - returns a new authentication token.
  /api/CashTransactions:
    post:
      requestBody:
        description: This is cash transaction request contract.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashTransactionRequest'
      tags:
      - Cash Transactions
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
          description: Success response for cash transaction
      deprecated: true
      summary: Post a cash transaction to masterpiece. Deprecated as of December 2021
        - replaced by OnlinePayments.
  /api/invoicenumbers/generation/{clientId}:
    get:
      tags:
      - Invoice Numbers
      parameters:
      - name: clientId
        description: A string value stored within the system that identifies the client.
        schema:
          type: string
        in: path
        required: true
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceNumberResponse'
          description: Successful response - returns an Invoice number.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResult'
          description: Bad Request
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResult'
          description: Conflict
      summary: Generate an invoice number for a client system
      description: Generates an invoice number specific to the client.
  /api/invoicenumbers/configuration/{clientId}:
    get:
      tags:
      - Invoice Numbers
      parameters:
      - name: clientId
        schema:
          type: string
        in: path
        required: true
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientConfigurationResponse'
          description: Successful response - returns client configuration settings.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResult'
          description: Bad Request
      summary: Retrieve client configuration settings
  /api/invoicenumbers/configuration:
    get:
      tags:
      - Invoice Numbers
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientConfigurationResponse'
          description: Successful response - returns a collection of all client configuration
            settings.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResult'
          description: Bad Request
      summary: Retrieve client configuration settings
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientConfigurationRequest'
      tags:
      - Invoice Numbers
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientConfigurationResponse'
          description: Successful response - returns new client configuration.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResult'
          description: Bad Request
      summary: Create a client configuration
  /api/OnlinePayments:
    post:
      requestBody:
        description: This is the online payment request contract.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashTransactionRequest'
      tags:
      - Online Payments
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
          description: Success response for online payments
      summary: Post an online payment to masterpiece
  /api/paymentcollections:
    post:
      requestBody:
        description: This is Payment collection request contract.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCollectionRequest'
      tags:
      - Payment Collections
      parameters:
      - name: api-version
        description: The requested API version
        schema:
          default: "1.0"
        in: header
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
          description: Success response for Payment Collection transaction
      summary: Post a payment collection request to masterpiece
components:
  schemas:
    TokenRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      additionalProperties: false
    TokenResponse:
      type: object
      properties:
        token:
          nullable: true
          type: string
      additionalProperties: false
    LineItem:
      required:
      - glCode
      - netPriceFull
      - productCode
      - productDescription
      - quantity
      - taxCode
      - taxRate
      - totalTax
      type: object
      properties:
        netPriceFull:
          format: double
          type: number
        taxCode:
          type: string
        taxRate:
          format: double
          type: number
        quantity:
          format: int32
          type: integer
        productCode:
          type: string
        productDescription:
          type: string
        glCode:
          type: string
        totalTax:
          format: double
          type: number
      additionalProperties: false
    PurchasePaymentDetail:
      required:
      - paymentReceivedAmount
      - paymentReferenceNumber
      type: object
      properties:
        paymentReceivedAmount:
          format: double
          type: number
        paymentReferenceNumber:
          type: string
      additionalProperties: false
    PurchaseDetail:
      required:
      - customerId
      - dueDate
      - invoiceId
      - lineItems
      - purchaseNetAmount
      - purchasePaymentDetails
      - purchaseTaxAmount
      - purchaseTotalAmount
      - transactionDate
      type: object
      properties:
        customerId:
          type: string
        transactionDate:
          format: date-time
          type: string
        dueDate:
          format: date-time
          type: string
        invoiceId:
          type: string
        purchaseNetAmount:
          format: double
          type: number
        purchaseTaxAmount:
          format: double
          type: number
        purchaseTotalAmount:
          format: double
          type: number
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        purchasePaymentDetails:
          type: array
          items:
            $ref: '#/components/schemas/PurchasePaymentDetail'
      additionalProperties: false
    CashTransactionRequest:
      required:
      - clientId
      - purchaseDetails
      - transactionGroupDate
      type: object
      properties:
        transactionGroupDate:
          format: date-time
          description: Its a transaction processing date / batch date for masterpiece
          type: string
        purchaseDetails:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseDetail'
        clientId:
          type: string
      additionalProperties: false
    TransactionResponse:
      type: object
      properties:
        result:
          nullable: true
          type: string
        batchNumber:
          nullable: true
          type: string
      additionalProperties: false
    InvoiceNumberResponse:
      type: object
      properties:
        invoiceNumber:
          nullable: true
          type: string
      additionalProperties: false
    ConflictResult:
      type: object
      properties:
        statusCode:
          format: int32
          type: integer
          readOnly: true
      additionalProperties: false
    BadRequestResult:
      type: object
      properties:
        statusCode:
          format: int32
          type: integer
          readOnly: true
      additionalProperties: false
    ClientConfigurationResponse:
      type: object
      properties:
        id:
          format: int32
          type: integer
        clientId:
          nullable: true
          type: string
        clientFullname:
          nullable: true
          type: string
        prefix:
          nullable: true
          type: string
        suffix:
          nullable: true
          type: string
        filePrefix:
          nullable: true
          type: string
      additionalProperties: false
    ClientConfigurationRequest:
      required:
      - clientFullname
      - clientId
      type: object
      properties:
        clientId:
          maxLength: 7
          type: string
        clientFullname:
          type: string
        prefix:
          nullable: true
          maxLength: 3
          type: string
        suffix:
          nullable: true
          maxLength: 3
          type: string
        filePrefix:
          nullable: true
          maxLength: 3
          type: string
      additionalProperties: false
    RemittancePaymentDetail:
      required:
      - paymentAmount
      - transactionType
      type: object
      properties:
        invoiceNumber:
          nullable: true
          type: string
        paymentAmount:
          format: double
          type: number
        transactionType:
          type: string
      additionalProperties: false
    RemittanceDetail:
      required:
      - customerId
      - payments
      - remittanceDate
      - remmittanceId
      - totalRemittanceAmount
      type: object
      properties:
        remmittanceId:
          type: string
        remittanceDate:
          format: date-time
          type: string
        totalRemittanceAmount:
          format: double
          type: number
        customerId:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/RemittancePaymentDetail'
      additionalProperties: false
    PaymentCollectionRequest:
      required:
      - batchDate
      - clientId
      - remittances
      type: object
      properties:
        batchDate:
          format: date-time
          type: string
        clientId:
          type: string
        remittances:
          type: array
          items:
            $ref: '#/components/schemas/RemittanceDetail'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
        Bearer {token}"'
      name: Authorization
      in: header
security:
- Bearer: []
tags:
- name: Cash Transactions
  description: ""
- name: Invoice Numbers
  description: ""
- name: Online Payments
  description: ""
- name: Payment Collections
  description: ""
- name: Auth
  description: ""
